name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

#Não irá funcionar pois não contém as variaveis de ambiente dentro do repositorio para acesso a AWS e acesso ao ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t hello-world-js .

 #O secrets.ECR_URI é o URI do repositorio do ECR que foi criado dentro da AWS
      - name: Tag Docker image
        run: |
          docker tag hello-world-app:latest ${{ secrets.ECR_URI }}:latest

#Não irá funcionar a parte de Push pois não contém a URI do Repositorio ECR dentro das Secrets
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_URI }}:latest
